[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
multiboot = "0.8.0"

[toolchain]
channel = "nightly"