[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/main.rs"
crate-type = ["staticlib"]

[unstable]
build-std = ["core"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"